### ISSUE TITLE
Error retrieving 2checkout order

### ISSUE THREAD

**Issue by rkevinn** [2Checkout/2checkout-node-sdk#1]
I am getting 'tco.order is not a function' error. 

I am trying to retrieve order details from 2checkout using tco.order().retrieve() method.
```
const Twocheckout = require("2checkout-nodejs");

try {
const tco = new Twocheckout({sellerId: "XXXXXXXX", secretKey: "XXXXXXXXX"});
let response = await tco.order().retrieve({ RefNo: “123123” });
} catch (error) {
throw error;
}
```

**Comment by craigchristenson** [comment]
I am sorry for the confusion here. It looks like you are using the legacy 2checkout node extension. You will need to install this extension to use this method.

Example package.json dependency
```json
"twocheckout": "2Checkout/2checkout-node-sdk#v1.1.1"
```
